CREATE TABLE IF NOT EXISTS T_CUSTOMERS (
    ID BIGINT NOT NULL AUTO_INCREMENT,
    NAME VARCHAR(255) NOT NULL,
    SURNAME VARCHAR(255) NOT NULL,
    AGE CHAR(3),
    PRIMARY KEY(ID)
)ENGINE=InnoDB DEFAULT CHARSET utf8;

CREATE TABLE IF NOT EXISTS T_CONTACTS (
    ID BIGINT NOT NULL AUTO_INCREMENT,
    CUSTOMER_ID BIGINT NOT NULL,
    TYPE INT NOT NULL,
    CONTACT VARCHAR(255) NOT NULL,
    PRIMARY KEY(ID),
    FOREIGN KEY(CUSTOMER_ID) REFERENCES T_CUSTOMERS(ID)
)ENGINE=InnoDB DEFAULT CHARSET utf8;